services:
  proxy:
    container_name: proxy
    image: caddy:2.11-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    depends_on:
      - client
      - server

  client:
    container_name: client
    build: client
    expose:
      - 3001

  server:
    container_name: server
    build: server
    expose:
      - 3000
    volumes:
      - ./.volumes/sc3d:/app/sc3d
    environment:
      - ORIGIN_ALLOWED=http://localhost
      - PORT=3000
      - ASSETS_DIRECTORY=/app/sc3d
      - BLENDER_DIRECTORY=/usr/bin/blender

volumes:
  caddy_data:
  caddy_config: