services:
  proxy:
    container_name: proxy
    build: proxy
    ports:
      - 80:80
    depends_on:
      - client
      - server

  client:
    container_name: client
    build: client
    expose:
      - 3001

  server:
    container_name: server
    build: server
    expose:
      - 3000
    volumes:
      - ./.volumes/sc3d:/app/sc3d
    environment:
      - ORIGIN_ALLOWED=http://localhost
      - PORT=3000
      - ASSETS_DIRECTORY=/app/sc3d
      - BLENDER_DIRECTORY=/usr/bin/blender